### ISSUE TITLE
Archived TODO

### ISSUE THREAD

**Issue by purplecabbage** [phonegap/phonegap-app-stockpile#34]
Pasted from another project 
From @hollyschinsky:
- [x] Review/merge 3 outstanding pull requests for Split Panel template
- [x] Implement any feedback from users of docs (Herm)
- [ ] Update a couple screenshots due to side menu background color change PR
- [ ] Add a blurb about the icons?
- [x] Determining best location for docs based on current docs structure/side menu
- [x] Blog post written
- [x] If we include all templates in the announcement, one additional to do is to ensure they're all updated with the latest changes we agreed on in yesterday's call
- [ ] Add Adobe code headers to Stockpile

**Comment by purplecabbage** [comment]
from @devgeeks 
> If we include all templates in the announcement, one additional to do is to ensure they're all updated with the latest changes we agreed on in yesterday's call

I have started the process of updating `tabs` and `blank`. I still have a few outstanding issues... including the mother of all of them which is adding the PWA features.
